name: sgcafmaps
channels:
  - pytorch
  - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - chardet=3.0.4=py38h06a4308_1003
  - cryptography=39.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h9edb442_10
  - decorator=4.4.2=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=2.9=py_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1t=h7f8727e_0
  - pip=22.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.14.0=py38h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.34.2
    - addict==2.4.0
    - aenum==3.1.16
    - aiofiles==22.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - aiosqlite==0.20.0
    - albumentations==1.3.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - anykeystore==0.2
    - apex==0.9.10.dev0
    - appdirs==1.4.4
    - argcomplete==3.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-timeout==5.0.1
    - asynctest==0.13.0
    - attrs==22.2.0
    - av==12.3.0
    - av2==0.2.1
    - babel==2.15.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blinker==1.8.2
    - blosc==1.11.1
    - build==1.2.2.post1
    - cachecontrol==0.14.2
    - cachetools==5.3.2
    - ccimport==0.3.7
    - charset-normalizer==3.3.2
    - chumpy==0.70
    - clearml==1.16.2
    - cleo==2.1.0
    - click==8.1.7
    - cmake==3.30.1
    - codecov==2.1.12
    - colorlog==6.8.2
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.0.7
    - coverage==7.2.2
    - crashtest==0.4.1
    - cryptacular==1.6.2
    - cumm-cu113==0.2.9
    - cupy==12.3.0
    - cvpods==0.1+cu113torch110
    - cycler==0.11.0
    - cython==0.29.33
    - dash==2.17.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.2
    - defusedxml==0.7.1
    - deltaconv==1.0.2
    - deprecation==2.1.0
    - detectron==0.0.0
    - diffusers==0.25.0
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - dq3d==0.3.6
    - dulwich==0.21.7
    - entrypoints==0.4
    - exceptiongroup==1.1.1
    - executing==2.0.1
    - faiss-gpu==1.7.2
    - fastgeodis==1.0.5
    - fastjsonschema==2.20.0
    - fastrlock==0.8.3
    - fire==0.6.0
    - flake8==6.0.0
    - flask==3.0.3
    - fonttools==4.39.2
    - fqdn==1.5.1
    - frozenlist==1.5.0
    - furl==2.1.3
    - fvcore==0.1.5.post20221221
    - geomloss==0.2.6
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.23.3
    - google-auth-oauthlib==1.0.0
    - greenlet==3.1.1
    - grpcio==1.59.0
    - h5py==3.11.0
    - hupper==1.12.1
    - hydra-core==1.3.2
    - imagecorruptions==1.1.0
    - imageio==2.8.0
    - imgaug==0.4.0
    - importlib-metadata==6.8.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - installer==0.7.0
    - iopath==0.1.10
    - ipykernel==6.29.5
    - ipython==8.12.3
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.3
    - isoduration==20.11.0
    - isort==5.12.0
    - itsdangerous==2.2.0
    - jaraco-classes==3.4.0
    - jedi==0.19.1
    - jeepney==0.9.0
    - jinja2==3.1.4
    - joblib==1.2.0
    - json-tricks==3.16.1
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==7.4.9
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-packaging==0.12.3
    - jupyter-server==2.14.2
    - jupyter-server-fileid==0.9.2
    - jupyter-server-terminals==0.5.3
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.5
    - jupyterlab==3.6.7
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.11
    - keopscore==2.2.3
    - keyring==24.3.1
    - kiwisolver==1.2.0
    - kornia==0.7.3
    - kornia-rs==0.1.5
    - lark==1.1.9
    - lazy-loader==0.1
    - libigl==2.5.1
    - lightly==1.5.20
    - lightly-utils==0.0.2
    - lightning-utilities==0.11.9
    - llvmlite==0.41.1
    - markdown==3.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.2.1
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mistune==3.0.2
    - mmcv-full==1.7.1
    - mmdet==1.0rc1+unknown
    - mmpose==0.29.0
    - more-itertools==10.5.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - munkres==1.1.4
    - nbclassic==1.1.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==2.4
    - ninja==1.11.1
    - notebook==6.5.7
    - notebook-shim==0.2.4
    - nox==2024.4.15
    - numba==0.58.1
    - numpy==1.18.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.41
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open3d==0.14.1
    - opencv-contrib-python==4.7.0.72
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - orderedmultidict==1.0.1
    - overrides==7.7.0
    - packaging==25.0
    - pandas==1.0.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pastedeploy==3.1.0
    - pathlib2==2.3.7.post1
    - pathspec==0.12.1
    - pbkdf2==1.3
    - pccm==0.3.4
    - pcdet==0.6.0+0
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkginfo==1.12.1.2
    - pkgutil-resolve-name==1.3.10
    - plaster==1.1.2
    - plaster-pastedeploy==1.0.1
    - platformdirs==4.2.2
    - plotly==5.22.0
    - pluggy==1.0.0
    - poetry==1.8.5
    - poetry-core==1.9.1
    - poetry-plugin-export==1.8.0
    - pointnet2==0.0.0
    - polyscope==2.4.0
    - pooch==1.8.2
    - pot==0.9.4
    - potpourri3d==1.2.1
    - probreg==0.3.8
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.47
    - propcache==0.2.0
    - protobuf==4.24.4
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==17.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.13.1
    - pycocotools==2.0.6
    - pycodestyle==2.10.0
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pyflakes==3.0.1
    - pygifsicle==1.1.0
    - pygments==2.18.0
    - pyjwt==2.8.0
    - pykeops==2.2.3
    - pykitti==0.3.1
    - pyparsing==3.0.9
    - pyproj==3.5.0
    - pyproject-hooks==1.2.0
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.17
    - pyqt5-sip==12.15.0
    - pyquaternion==0.9.9
    - pyramid==2.0.2
    - pyramid-mailer==0.15.1
    - pyshell==0.1.1
    - pytest==7.2.2
    - pytest-cov==4.0.0
    - python-dateutil==2.8.1
    - python-json-logger==2.0.7
    - python-version==0.0.2
    - python3-openid==3.2.0
    - pytorch-lightning==2.4.0
    - pytorch-metric-learning==2.6.0
    - pytz==2020.1
    - pyvista==0.44.1
    - pywavelets==1.4.1
    - pyyaml==5.4
    - pyzmq==26.0.3
    - qudida==0.0.4
    - rapidfuzz==3.9.7
    - referencing==0.35.1
    - regex==2024.9.11
    - repoze-sendmail==4.4.1
    - requests==2.32.3
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - robust-laplacian==1.0.0
    - rpds-py==0.18.1
    - rsa==4.9
    - scikit-build-core==0.11.2
    - scikit-image==0.17.1
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - scooby==0.10.0
    - secretstorage==3.3.3
    - send2trash==1.8.3
    - sentry-sdk==2.11.0
    - setproctitle==1.3.3
    - shapely==2.0.7
    - sharedarray==3.2.4
    - shellingham==1.5.4
    - sklearn==0.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - spconv-cu113==2.1.25
    - sqlalchemy==2.0.36
    - stack-data==0.6.3
    - sympy==1.13.3
    - tenacity==8.5.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - terminado==0.18.1
    - terminaltables==3.1.10
    - threadpoolctl==3.1.0
    - tifffile==2023.3.15
    - tinycss2==1.3.0
    - tokenizers==0.19.1
    - tomli==2.0.1
    - tomlkit==0.13.0
    - torch==1.12.0+cu113
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2
    - torchaudio==0.12.0+cu113
    - torchdiffeq==0.2.4
    - torchmetrics==1.5.2
    - torchvision==0.13.0+cu113
    - tornado==6.4.1
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transaction==5.0
    - transformations==2022.9.26
    - transformers==4.44.2
    - transforms3d==0.4.2
    - translationstring==1.4
    - trimesh==4.6.5
    - triton==3.0.0
    - trove-classifiers==2025.5.9.12
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.12.2
    - uri-template==1.3.0
    - urllib3==1.26.5
    - velruse==1.1.1
    - venusian==3.1.1
    - virtualenv==20.31.2
    - vtk==9.3.1
    - wandb==0.17.5
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - webob==1.8.9
    - websocket-client==1.8.0
    - werkzeug==3.0.1
    - wheel==0.43.0
    - widgetsnbextension==4.0.11
    - wtforms==3.1.2
    - wtforms-recaptcha==0.3.2
    - xdoctest==1.1.1
    - xtcocotools==1.13
    - y-py==0.6.2
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.15.2
    - ypy-websocket==0.8.4
    - zipp==3.15.0
    - zope-deprecation==5.0
    - zope-interface==7.2
    - zope-sqlalchemy==3.1
